const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const main={innerHTML:'',scrollTop:0},dialog={open:false,dataset:{},scrollTop:0},content={innerHTML:''};
let focused=0,selected=null,detail=null,readCalls=0,renderCalls=0;const resolvers=[],messages=[],events={};
const field={id:'plugin-search',dataset:{},selectionStart:2,selectionEnd:4,focus(){focused++},setSelectionRange(a,b){selected=[a,b]}};
const ctx={window:{},console,Map,Set,document:{activeElement:{},getElementById:id=>id==='plugin-search'?field:null,addEventListener:(name,fn)=>events[name]=fn},matchMedia:()=>({matches:true}),data:{settings:{motion:false}},page:'plugins',backendState:{pluginTab:'plugins',pluginCategory:'all',pluginScope:'host',pluginState:'all',pluginPage:0,pluginSearch:'',pluginData:null,pluginPending:new Set(),pluginFeedback:new Map(),pluginRequest:0,status:'connected'},$:s=>s==='#main'?main:s==='#detail-dialog'?dialog:s==='#dialog-content'?content:s==='#detail-dialog [data-detail-id]'?detail:s==='#plugin-search'?field:null,$$:()=>[],escapeHTML:v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pageHeader:()=>'<header>Plugins</header>',icon:()=>'<svg></svg>',backendPluginName:i=>i.meta?.title||i.moduleName||i.name||'Plugin',localizedPluginText:(v,f='')=>typeof v==='string'?v:v?.en||f,backendPluginRelations:i=>i.relatedPlugins||[],openDialog:html=>{content.innerHTML=html;dialog.open=true;},closeDialog:()=>{dialog.open=false;},toast:s=>messages.push(s),save:()=>{},dialogFocus:null,backend:{listPlugins:()=>{readCalls++;return new Promise(resolve=>resolvers.push(resolve));}},renderBackendPlugins:()=>renderCalls++};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/plugin-library.js','utf8'),ctx);
const L=ctx.window.AsterPluginLibrary,U=ctx.window.AsterPluginUI;
assert.equal(L.classify({moduleName:'@deepseek-ai/dsh-schedule'}).role,'feature');
assert.equal(L.classify({moduleName:'cordis:include'}).role,'system');
assert.equal(L.classify({moduleName:'cordis:group'}).role,'system');
assert.equal(L.classify({moduleName:'@custom/schedule'}).role,'unknown');
const plugin={entryId:'root/tool',patchId:'tool',moduleName:'@custom/tool',enabled:false};
const bundle={name:'box',installed:true,removable:true,enabled:true,rows:[{entryId:'root/tool',rowId:'tool',moduleName:'@custom/tool'}],overrides:['llm']};
assert.equal(L.classify(plugin,[bundle]).category,'extension');
assert.equal(L.classify({...plugin,moduleName:'@different/replacement'},[bundle]).category,'unknown');
assert.equal(L.classify({moduleName:'@custom/plugin',readOnlyReason:'management-required'}).role,'unknown');
const preset={id:'standard',rows:[{entryId:'one',moduleName:'@deepseek-ai/dsh-tool-fs',enabled:'conditional'},{entryId:'two',moduleName:'@deepseek-ai/dsh-tool-web',enabled:false}]};
const keys=L.scopedRows({agentPresets:[preset]},'preset:standard').map(L.key);
const reordered=L.scopedRows({agentPresets:[{...preset,rows:[...preset.rows].reverse()}]},'preset:standard').map(L.key);
assert.equal(keys[0],reordered[1]);assert.equal(keys[1],reordered[0]);
const state={available:true,bundles:[bundle],plugins:Array.from({length:40},(_,n)=>({entryId:'tool-'+n,patchId:'tool-'+n,moduleName:'@deepseek-ai/dsh-tool-fs',enabled:n%2===0,fiberPhase:n%2===0?'active':null,meta:{title:n===0?'<img src=x onerror=alert(1)>':'Tool '+n}})),agentPresets:[preset]};
ctx.backendState.pluginData=state;U.render(false);
assert.equal((main.innerHTML.match(/data-open-plugin=/g)||[]).length,16);assert.ok(!main.innerHTML.includes('<img src=x'));
ctx.document.activeElement=field;U.render(false);assert.equal(focused,1);assert.deepEqual(selected,[2,4]);
ctx.backendState.pluginSearchComposing=true;main.innerHTML='keep composing';U.render(false);assert.equal(main.innerHTML,'keep composing');ctx.backendState.pluginSearchComposing=false;
ctx.backendState.pluginScope='preset:removed';ctx.backendState.pluginPage=5;U.render(false);assert.equal(ctx.backendState.pluginScope,'host');assert.equal(ctx.backendState.pluginPage,0);
ctx.backendState.pluginScope='preset:standard';U.render(false);U.open('plugin',keys[0]);assert.ok(content.innerHTML.includes('Conditional'));assert.ok(/data-plugin-action="toggle"[^>]*disabled/.test(content.innerHTML));
ctx.backendState.pluginScope='host';dialog.open=false;U.open('plugin','tool-1');assert.ok(content.innerHTML.includes('Enable · 启用'));
detail={dataset:{detailKind:'plugin',detailId:'tool-1'}};state.plugins[1].enabled=true;state.plugins[1].fiberPhase='active';U.syncDetail();assert.ok(content.innerHTML.includes('Turn off · 关闭'));
ctx.backendState.status='disconnected';U.syncDetail();assert.ok(content.innerHTML.includes('连接已断开'));assert.ok(/data-plugin-action="toggle"[^>]*disabled/.test(content.innerHTML));ctx.backendState.status='connected';
ctx.backendState.pluginPending.add('plugin:other');U.open('plugin','tool-1');assert.ok(content.innerHTML.includes('等待更改完成'));assert.ok(/data-plugin-action="toggle"[^>]*disabled/.test(content.innerHTML));ctx.backendState.pluginPending.clear();
U.relation('tool-1','missing');assert.ok(messages.at(-1).includes('关联已不在'));
const app=fs.readFileSync('dist/app.js','utf8'),a=app.indexOf("document.addEventListener('compositionstart'"),b=app.indexOf("$('#detail-dialog').addEventListener('cancel'",a);vm.runInContext(app.slice(a,b),ctx);
events.compositionstart({target:field});events.input({target:{...field,value:'终'},isComposing:true});assert.equal(renderCalls,0);events.compositionend({target:{...field,value:'终端'}});assert.equal(renderCalls,1);assert.equal(ctx.backendState.pluginSearch,'终端');
(async()=>{
 dialog.open=false;detail=null;ctx.document.activeElement={};ctx.backendState.pluginSearch='';
 const first=U.fetchInventory();U.fetchInventory();assert.equal(readCalls,1);resolvers.shift()(state);await first;assert.equal(readCalls,2);resolvers.shift()(state);await new Promise(r=>setImmediate(r));assert.equal(ctx.backendState.pluginLoading,false);assert.equal(ctx.backendState.pluginRefreshQueued,false);
 console.log('PASS targeted review: provenance collision, preset reordering, pagination scope fallback, focus/selection, IME, stale dialog refresh, disconnect protection, mutation serialization, missing relation, refresh coalescing.');
})().catch(e=>{console.error(e);process.exitCode=1});
